; Xidi SDL3 Plugin
; Allows to use modern SDL3-based controllers like Steam Controller 2.
Plugin = SDL
ControllerBackend = SDL3

[Mapper]
Type			= SH2EE

[Log]
Enabled = no
Level = 4

[CustomMapper:SH2EE]
; Imports all of the element mappers from StandardGamepad.
; This line is allowed to appear anywhere in the section, including between or after the element mappers below.
Template		= StandardGamepad

; These changes are applied on top of the template.
ButtonA			= Button(2)
ButtonB			= Button(3)
ButtonX			= Button(1)
ButtonY			= Button(4)
