echo off

rem ****
echo Creating ADX files
rem ****

adxencd 1fwb_rain.wav
adxencd 62_0A.wav
adxencd 703_a.wav
adxencd 703_b.wav
adxencd 703_c.wav
adxencd aijin.wav
adxencd aijin_2.wav
adxencd aijin_2a.wav
adxencd aijin_2b.wav
adxencd aijin_2b_mix.wav
adxencd ana_1.wav
adxencd ap_boss.wav
adxencd be_mae_2.wav
adxencd boilers.wav
adxencd boilers_l.wav
adxencd bort_1.wav
adxencd bort_2.wav
adxencd bp_edi_1_a.wav
adxencd bp_edi_1_b.wav
adxencd bp_edi_2.wav
adxencd bp_edi_3.wav
adxencd bp_mae.wav
adxencd bp_mar_tsuika.wav
adxencd byouin_exit.wav
adxencd byouin_hairu.wav
adxencd byouin_lau.wav
adxencd chasaw_h_46.wav
adxencd chasaw_l_45.wav
adxencd CHEN_WO.wav
adxencd clock_4.wav
adxencd dust_1.wav
adxencd dust_ju_6.wav
adxencd edi_korosu_1.wav
adxencd edi_korosu_2.wav
adxencd elev_move_12.wav
adxencd fan_go.wav
adxencd fire_agl.wav
adxencd forest_wind.wav
adxencd fukkatsu.wav
adxencd fukkatsu_2.wav
adxencd GAME_OVER.wav
adxencd geki.wav
adxencd gekijyou_1.wav
adxencd gekijyou_2.wav
adxencd gekijyou_3.wav
adxencd gero_ed.wav
adxencd gero_edi_1.wav
adxencd gero_edi_2.wav
adxencd gero_edi_3.wav
adxencd goki_jet.wav
adxencd go_to_ura_1.wav
adxencd go_to_ura_2.wav
adxencd g_start.wav
adxencd hakaba_agl_1.wav
adxencd hakaba_agl_2.wav
adxencd hakaba_agl_3.wav
adxencd harigane.wav
adxencd hei.wav
adxencd henjee_1.wav
adxencd henjee_2.wav
adxencd hiroba.wav
adxencd hotel_d1_cl.wav
adxencd inai.wav
adxencd ind_ev_mv.wav
adxencd inoru_onna.wav
adxencd inuend_bgm.wav
adxencd jisatsu.wav
adxencd jisatsu_2.wav
adxencd jump_1.wav
adxencd jump_2.wav
adxencd jump_3.wav
adxencd jump_4.wav
adxencd jump_5.wav
adxencd kagikeri_1.wav
adxencd kanaami.wav
adxencd kao.wav
adxencd killer_edi_1.wav
adxencd killer_edi_2.wav
adxencd killer_edi_3.wav
adxencd killer_edi_4.wav
adxencd kitanai_1.wav
adxencd knife_agl.wav
adxencd kokuchi.wav
adxencd kubituri.wav
adxencd lakeside.wav
adxencd lau_damasu_1.wav
adxencd lau_damasu_2.wav
adxencd lau_damasu_3.wav
adxencd letter_water.wav
adxencd letter_water_st.wav
adxencd maria_2dead.wav
adxencd mary_let_fix.wav
adxencd mar_dead_1.wav
adxencd mar_dead_2_1.wav
adxencd mar_dead_2_2.wav
adxencd mar_deai_1.wav
adxencd mar_deai_2.wav
adxencd mar_end_roll.wav
adxencd mar_hagureru_1.wav
adxencd mar_hagureru_2.wav
adxencd mar_hagureru_3.wav
adxencd mar_ikiteruka_1.wav
adxencd mar_ikiteruka_2.wav
adxencd mar_saikai_1.wav
adxencd mar_saikai_2.wav
adxencd meabos_mori.wav
adxencd mizu_hiki.wav
adxencd mry_rakka.wav
adxencd mukashi_room_2.wav
adxencd m_deai_tsuika.wav
adxencd nageru.wav
adxencd nuigurumi_1.wav
adxencd nuigurumi_2.wav
adxencd papa_agl_1.wav
adxencd papa_agl_2.wav
adxencd papa_agl_3.wav
adxencd piano_1.wav
adxencd piano_2.wav
adxencd pipe_car_e.wav
adxencd QUIZ.wav
adxencd radio_43.wav
adxencd reisouko_1.wav
adxencd reisouko_2.wav
adxencd saisho_1.wav
adxencd saisho_2.wav
adxencd saisho_3.wav
adxencd sankaku_jisatsu.wav
adxencd sankaku_toujyou.wav
adxencd sankaku_vs.wav
adxencd satsugai.wav
adxencd save_sound.wav
adxencd SCENE_01.wav
adxencd SCENE_02.wav
adxencd SCENE_45.wav
adxencd SCENE_53.wav
adxencd silen.wav
adxencd splay_at_48.wav
adxencd suiteki.wav
adxencd surprise_01.wav
adxencd surprise_02.wav
adxencd surprise_03.wav
adxencd surprise_07.wav
adxencd tejyou.wav
adxencd tobira_mado_1.wav
adxencd tobira_mado_2.wav
adxencd tobira_mado_3.wav
adxencd toile_nok.wav
adxencd tsuri_1.wav
adxencd tv_noiz_1.wav
adxencd UFO_1.wav
adxencd UFO_2.wav
adxencd UFO_END.wav
adxencd WATER_MARY.wav
adxencd what_amy.wav
adxencd what_amy_ato.wav
adxencd yarinaoshi.wav
adxencd yarinaoshi_2_2.wav
adxencd yarinaoshi_letter.wav
adxencd YARINAOSHI_LETTER_MIX.wav

rem ****
echo Create folders and move files to folders
rem ****

md ADX
move /y *.adx ADX