name: CI

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  UseMultiToolTask: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Workflow]
        platform: [Win32]

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Setup MSBuild
      shell: pwsh
      run: |
        $msbuild = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
          -latest `
          -requires Microsoft.Component.MSBuild `
          -find MSBuild\**\Bin\MSBuild.exe

        if (-not $msbuild) { throw "MSBuild not found." }

        $msbuildDir = Split-Path $msbuild
        Add-Content $env:GITHUB_PATH $msbuildDir

    - name: Build
      run: msbuild sh2-enhce.sln /m /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }}

    - uses: actions/upload-artifact@v6
      with:
        name: ${{ matrix.config }} binaries
        path: |
          bin/${{ matrix.config }}/*
