name: CI

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  UseMultiToolTask: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Workflow]
        platform: [Win32]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: microsoft/setup-msbuild@v1
    - uses: Trass3r/setup-cpp@master
    - name: Build
      run: msbuild /m /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }} sh2-enhce.sln
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config }} binaries
        path: |
          bin/${{ matrix.config }}/*
